/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'teacherId' : IDL.Nat,
  'recordId' : IDL.Nat,
});
export const ClassLevel = IDL.Record({
  'id' : IDL.Nat,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'monthlyFee' : IDL.Nat,
});
export const DemoBooking = IDL.Record({
  'status' : IDL.Text,
  'bookingId' : IDL.Nat,
  'studentName' : IDL.Text,
  'createdAt' : IDL.Nat,
  'classLevel' : IDL.Text,
  'cityVillage' : IDL.Text,
  'mobile' : IDL.Text,
  'parentName' : IDL.Text,
  'medium' : IDL.Text,
});
export const Homework = IDL.Record({
  'title' : IDL.Text,
  'homeworkId' : IDL.Nat,
  'createdAt' : IDL.Nat,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'teacherId' : IDL.Nat,
  'classLevel' : IDL.Text,
});
export const Payment = IDL.Record({
  'razorpayPaymentId' : IDL.Text,
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
  'planId' : IDL.Nat,
  'createdAt' : IDL.Nat,
  'razorpayOrderId' : IDL.Text,
  'paymentId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const PricingPlan = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'planId' : IDL.Nat,
  'name' : IDL.Text,
  'isPopular' : IDL.Bool,
  'monthlyPrice' : IDL.Nat,
});
export const Referral = IDL.Record({
  'studentId' : IDL.Nat,
  'createdAt' : IDL.Nat,
  'isPaid' : IDL.Bool,
  'referralId' : IDL.Nat,
  'commissionAmount' : IDL.Nat,
  'fieldExecId' : IDL.Nat,
});
export const ScheduledClass = IDL.Record({
  'subject' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'classId' : IDL.Nat,
  'meetingLink' : IDL.Text,
  'teacherId' : IDL.Nat,
  'classLevel' : IDL.Text,
});
export const Student = IDL.Record({
  'studentId' : IDL.Nat,
  'enrolledPlanId' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'referredBy' : IDL.Opt(IDL.Nat),
  'classLevel' : IDL.Text,
  'parentId' : IDL.Nat,
  'syllabus' : IDL.Text,
  'medium' : IDL.Text,
});
export const StudyMaterial = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : IDL.Nat,
  'description' : IDL.Text,
  'materialId' : IDL.Nat,
  'teacherId' : IDL.Nat,
  'classLevel' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const TestResult = IDL.Record({
  'studentId' : IDL.Nat,
  'maxScore' : IDL.Nat,
  'subject' : IDL.Text,
  'testDate' : IDL.Text,
  'score' : IDL.Nat,
  'resultId' : IDL.Nat,
});
export const Certificate = IDL.Record({
  'issueDate' : IDL.Text,
  'certId' : IDL.Nat,
  'studentId' : IDL.Nat,
  'certNumber' : IDL.Text,
  'courseName' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'Parent' : IDL.Null,
  'Teacher' : IDL.Null,
  'Student' : IDL.Null,
  'FieldExecutive' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'role' : AppRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'createAttendanceRecord' : IDL.Func([AttendanceRecord], [], []),
  'createClassLevel' : IDL.Func([ClassLevel], [], []),
  'createDemoBooking' : IDL.Func([DemoBooking], [], []),
  'createHomework' : IDL.Func([Homework], [], []),
  'createPayment' : IDL.Func([Payment], [], []),
  'createPricingPlan' : IDL.Func([PricingPlan], [], []),
  'createRazorpayOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
  'createReferral' : IDL.Func([Referral], [], []),
  'createScheduledClass' : IDL.Func([ScheduledClass], [], []),
  'createStudent' : IDL.Func([Student], [], []),
  'createStudyMaterial' : IDL.Func([StudyMaterial], [], []),
  'createTestResult' : IDL.Func([TestResult], [], []),
  'deleteClassLevel' : IDL.Func([IDL.Nat], [], []),
  'deleteDemoBooking' : IDL.Func([IDL.Nat], [], []),
  'deleteHomework' : IDL.Func([IDL.Nat], [], []),
  'deletePricingPlan' : IDL.Func([IDL.Nat], [], []),
  'deleteScheduledClass' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteStudyMaterial' : IDL.Func([IDL.Nat], [], []),
  'generateCertificate' : IDL.Func([IDL.Nat, IDL.Text], [Certificate], []),
  'getAllClassLevels' : IDL.Func([], [IDL.Vec(ClassLevel)], ['query']),
  'getAllDemoBookings' : IDL.Func([], [IDL.Vec(DemoBooking)], ['query']),
  'getAllPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
  'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertificatesByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Certificate)],
      ['query'],
    ),
  'getClassSchedule' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScheduledClass)],
      ['query'],
    ),
  'getDemoBooking' : IDL.Func([IDL.Nat], [DemoBooking], ['query']),
  'getHomeworkByClass' : IDL.Func([IDL.Text], [IDL.Vec(Homework)], ['query']),
  'getPaymentsByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getReferralsByFieldExec' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Referral)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
  'getStudentsByParent' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getStudentsByTeacher' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getStudyMaterials' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudyMaterial)],
      ['query'],
    ),
  'getTestResults' : IDL.Func([IDL.Nat], [IDL.Vec(TestResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Nat], [IDL.Opt(AppRole)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClassLevel' : IDL.Func([ClassLevel], [], []),
  'updateDemoBooking' : IDL.Func([DemoBooking], [], []),
  'updateHomework' : IDL.Func([Homework], [], []),
  'updatePricingPlan' : IDL.Func([PricingPlan], [], []),
  'updateScheduledClass' : IDL.Func([ScheduledClass], [], []),
  'updateStudent' : IDL.Func([Student], [], []),
  'updateStudyMaterial' : IDL.Func([StudyMaterial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'teacherId' : IDL.Nat,
    'recordId' : IDL.Nat,
  });
  const ClassLevel = IDL.Record({
    'id' : IDL.Nat,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'monthlyFee' : IDL.Nat,
  });
  const DemoBooking = IDL.Record({
    'status' : IDL.Text,
    'bookingId' : IDL.Nat,
    'studentName' : IDL.Text,
    'createdAt' : IDL.Nat,
    'classLevel' : IDL.Text,
    'cityVillage' : IDL.Text,
    'mobile' : IDL.Text,
    'parentName' : IDL.Text,
    'medium' : IDL.Text,
  });
  const Homework = IDL.Record({
    'title' : IDL.Text,
    'homeworkId' : IDL.Nat,
    'createdAt' : IDL.Nat,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'teacherId' : IDL.Nat,
    'classLevel' : IDL.Text,
  });
  const Payment = IDL.Record({
    'razorpayPaymentId' : IDL.Text,
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
    'planId' : IDL.Nat,
    'createdAt' : IDL.Nat,
    'razorpayOrderId' : IDL.Text,
    'paymentId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const PricingPlan = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'planId' : IDL.Nat,
    'name' : IDL.Text,
    'isPopular' : IDL.Bool,
    'monthlyPrice' : IDL.Nat,
  });
  const Referral = IDL.Record({
    'studentId' : IDL.Nat,
    'createdAt' : IDL.Nat,
    'isPaid' : IDL.Bool,
    'referralId' : IDL.Nat,
    'commissionAmount' : IDL.Nat,
    'fieldExecId' : IDL.Nat,
  });
  const ScheduledClass = IDL.Record({
    'subject' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'classId' : IDL.Nat,
    'meetingLink' : IDL.Text,
    'teacherId' : IDL.Nat,
    'classLevel' : IDL.Text,
  });
  const Student = IDL.Record({
    'studentId' : IDL.Nat,
    'enrolledPlanId' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'referredBy' : IDL.Opt(IDL.Nat),
    'classLevel' : IDL.Text,
    'parentId' : IDL.Nat,
    'syllabus' : IDL.Text,
    'medium' : IDL.Text,
  });
  const StudyMaterial = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'materialId' : IDL.Nat,
    'teacherId' : IDL.Nat,
    'classLevel' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const TestResult = IDL.Record({
    'studentId' : IDL.Nat,
    'maxScore' : IDL.Nat,
    'subject' : IDL.Text,
    'testDate' : IDL.Text,
    'score' : IDL.Nat,
    'resultId' : IDL.Nat,
  });
  const Certificate = IDL.Record({
    'issueDate' : IDL.Text,
    'certId' : IDL.Nat,
    'studentId' : IDL.Nat,
    'certNumber' : IDL.Text,
    'courseName' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'Parent' : IDL.Null,
    'Teacher' : IDL.Null,
    'Student' : IDL.Null,
    'FieldExecutive' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'role' : AppRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPayment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'createAttendanceRecord' : IDL.Func([AttendanceRecord], [], []),
    'createClassLevel' : IDL.Func([ClassLevel], [], []),
    'createDemoBooking' : IDL.Func([DemoBooking], [], []),
    'createHomework' : IDL.Func([Homework], [], []),
    'createPayment' : IDL.Func([Payment], [], []),
    'createPricingPlan' : IDL.Func([PricingPlan], [], []),
    'createRazorpayOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
    'createReferral' : IDL.Func([Referral], [], []),
    'createScheduledClass' : IDL.Func([ScheduledClass], [], []),
    'createStudent' : IDL.Func([Student], [], []),
    'createStudyMaterial' : IDL.Func([StudyMaterial], [], []),
    'createTestResult' : IDL.Func([TestResult], [], []),
    'deleteClassLevel' : IDL.Func([IDL.Nat], [], []),
    'deleteDemoBooking' : IDL.Func([IDL.Nat], [], []),
    'deleteHomework' : IDL.Func([IDL.Nat], [], []),
    'deletePricingPlan' : IDL.Func([IDL.Nat], [], []),
    'deleteScheduledClass' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteStudyMaterial' : IDL.Func([IDL.Nat], [], []),
    'generateCertificate' : IDL.Func([IDL.Nat, IDL.Text], [Certificate], []),
    'getAllClassLevels' : IDL.Func([], [IDL.Vec(ClassLevel)], ['query']),
    'getAllDemoBookings' : IDL.Func([], [IDL.Vec(DemoBooking)], ['query']),
    'getAllPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
    'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertificatesByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Certificate)],
        ['query'],
      ),
    'getClassSchedule' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScheduledClass)],
        ['query'],
      ),
    'getDemoBooking' : IDL.Func([IDL.Nat], [DemoBooking], ['query']),
    'getHomeworkByClass' : IDL.Func([IDL.Text], [IDL.Vec(Homework)], ['query']),
    'getPaymentsByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getReferralsByFieldExec' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Referral)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
    'getStudentsByParent' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getStudentsByTeacher' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getStudyMaterials' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudyMaterial)],
        ['query'],
      ),
    'getTestResults' : IDL.Func([IDL.Nat], [IDL.Vec(TestResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Nat], [IDL.Opt(AppRole)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClassLevel' : IDL.Func([ClassLevel], [], []),
    'updateDemoBooking' : IDL.Func([DemoBooking], [], []),
    'updateHomework' : IDL.Func([Homework], [], []),
    'updatePricingPlan' : IDL.Func([PricingPlan], [], []),
    'updateScheduledClass' : IDL.Func([ScheduledClass], [], []),
    'updateStudent' : IDL.Func([Student], [], []),
    'updateStudyMaterial' : IDL.Func([StudyMaterial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };