/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Parent' : null } |
  { 'Teacher' : null } |
  { 'Student' : null } |
  { 'FieldExecutive' : null } |
  { 'Admin' : null };
export interface AttendanceRecord {
  'status' : string,
  'studentId' : bigint,
  'date' : string,
  'teacherId' : bigint,
  'recordId' : bigint,
}
export interface Certificate {
  'issueDate' : string,
  'certId' : bigint,
  'studentId' : bigint,
  'certNumber' : string,
  'courseName' : string,
}
export interface ClassLevel {
  'id' : bigint,
  'subjects' : Array<string>,
  'name' : string,
  'monthlyFee' : bigint,
}
export interface DemoBooking {
  'status' : string,
  'bookingId' : bigint,
  'studentName' : string,
  'createdAt' : bigint,
  'classLevel' : string,
  'cityVillage' : string,
  'mobile' : string,
  'parentName' : string,
  'medium' : string,
}
export interface Homework {
  'title' : string,
  'homeworkId' : bigint,
  'createdAt' : bigint,
  'dueDate' : string,
  'description' : string,
  'teacherId' : bigint,
  'classLevel' : string,
}
export interface Payment {
  'razorpayPaymentId' : string,
  'status' : string,
  'studentId' : bigint,
  'planId' : bigint,
  'createdAt' : bigint,
  'razorpayOrderId' : string,
  'paymentId' : bigint,
  'amount' : bigint,
}
export interface PricingPlan {
  'features' : Array<string>,
  'planId' : bigint,
  'name' : string,
  'isPopular' : boolean,
  'monthlyPrice' : bigint,
}
export interface Referral {
  'studentId' : bigint,
  'createdAt' : bigint,
  'isPaid' : boolean,
  'referralId' : bigint,
  'commissionAmount' : bigint,
  'fieldExecId' : bigint,
}
export interface ScheduledClass {
  'subject' : string,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'classId' : bigint,
  'meetingLink' : string,
  'teacherId' : bigint,
  'classLevel' : string,
}
export interface Student {
  'studentId' : bigint,
  'enrolledPlanId' : bigint,
  'name' : string,
  'isActive' : boolean,
  'referredBy' : [] | [bigint],
  'classLevel' : string,
  'parentId' : bigint,
  'syllabus' : string,
  'medium' : string,
}
export interface StudyMaterial {
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'materialId' : bigint,
  'teacherId' : bigint,
  'classLevel' : string,
  'fileUrl' : string,
}
export interface TestResult {
  'studentId' : bigint,
  'maxScore' : bigint,
  'subject' : string,
  'testDate' : string,
  'score' : bigint,
  'resultId' : bigint,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : AppRole,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPayment' : ActorMethod<[bigint, string], boolean>,
  'createAttendanceRecord' : ActorMethod<[AttendanceRecord], undefined>,
  'createClassLevel' : ActorMethod<[ClassLevel], undefined>,
  'createDemoBooking' : ActorMethod<[DemoBooking], undefined>,
  'createHomework' : ActorMethod<[Homework], undefined>,
  'createPayment' : ActorMethod<[Payment], undefined>,
  'createPricingPlan' : ActorMethod<[PricingPlan], undefined>,
  'createRazorpayOrder' : ActorMethod<[bigint, bigint], string>,
  'createReferral' : ActorMethod<[Referral], undefined>,
  'createScheduledClass' : ActorMethod<[ScheduledClass], undefined>,
  'createStudent' : ActorMethod<[Student], undefined>,
  'createStudyMaterial' : ActorMethod<[StudyMaterial], undefined>,
  'createTestResult' : ActorMethod<[TestResult], undefined>,
  'deleteClassLevel' : ActorMethod<[bigint], undefined>,
  'deleteDemoBooking' : ActorMethod<[bigint], undefined>,
  'deleteHomework' : ActorMethod<[bigint], undefined>,
  'deletePricingPlan' : ActorMethod<[bigint], undefined>,
  'deleteScheduledClass' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'deleteStudyMaterial' : ActorMethod<[bigint], undefined>,
  'generateCertificate' : ActorMethod<[bigint, string], Certificate>,
  'getAllClassLevels' : ActorMethod<[], Array<ClassLevel>>,
  'getAllDemoBookings' : ActorMethod<[], Array<DemoBooking>>,
  'getAllPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getAttendanceByStudent' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertificatesByStudent' : ActorMethod<[bigint], Array<Certificate>>,
  'getClassSchedule' : ActorMethod<[string], Array<ScheduledClass>>,
  'getDemoBooking' : ActorMethod<[bigint], DemoBooking>,
  'getHomeworkByClass' : ActorMethod<[string], Array<Homework>>,
  'getPaymentsByStudent' : ActorMethod<[bigint], Array<Payment>>,
  'getReferralsByFieldExec' : ActorMethod<[bigint], Array<Referral>>,
  'getStudent' : ActorMethod<[bigint], Student>,
  'getStudentsByParent' : ActorMethod<[bigint], Array<Student>>,
  'getStudentsByTeacher' : ActorMethod<[bigint], Array<Student>>,
  'getStudyMaterials' : ActorMethod<[string], Array<StudyMaterial>>,
  'getTestResults' : ActorMethod<[bigint], Array<TestResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[bigint], [] | [AppRole]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClassLevel' : ActorMethod<[ClassLevel], undefined>,
  'updateDemoBooking' : ActorMethod<[DemoBooking], undefined>,
  'updateHomework' : ActorMethod<[Homework], undefined>,
  'updatePricingPlan' : ActorMethod<[PricingPlan], undefined>,
  'updateScheduledClass' : ActorMethod<[ScheduledClass], undefined>,
  'updateStudent' : ActorMethod<[Student], undefined>,
  'updateStudyMaterial' : ActorMethod<[StudyMaterial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];