/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ClassLevel {
    id: bigint;
    subjects: Array<string>;
    name: string;
    monthlyFee: bigint;
}
export interface Payment {
    razorpayPaymentId: string;
    status: string;
    studentId: bigint;
    planId: bigint;
    createdAt: bigint;
    razorpayOrderId: string;
    paymentId: bigint;
    amount: bigint;
}
export interface PricingPlan {
    features: Array<string>;
    planId: bigint;
    name: string;
    isPopular: boolean;
    monthlyPrice: bigint;
}
export interface ScheduledClass {
    subject: string;
    scheduledDate: string;
    scheduledTime: string;
    classId: bigint;
    meetingLink: string;
    teacherId: bigint;
    classLevel: string;
}
export interface DemoBooking {
    status: string;
    bookingId: bigint;
    studentName: string;
    createdAt: bigint;
    classLevel: string;
    cityVillage: string;
    mobile: string;
    parentName: string;
    medium: string;
}
export interface TestResult {
    studentId: bigint;
    maxScore: bigint;
    subject: string;
    testDate: string;
    score: bigint;
    resultId: bigint;
}
export interface StudyMaterial {
    title: string;
    createdAt: bigint;
    description: string;
    materialId: bigint;
    teacherId: bigint;
    classLevel: string;
    fileUrl: string;
}
export interface Referral {
    studentId: bigint;
    createdAt: bigint;
    isPaid: boolean;
    referralId: bigint;
    commissionAmount: bigint;
    fieldExecId: bigint;
}
export interface AttendanceRecord {
    status: string;
    studentId: bigint;
    date: string;
    teacherId: bigint;
    recordId: bigint;
}
export interface Homework {
    title: string;
    homeworkId: bigint;
    createdAt: bigint;
    dueDate: string;
    description: string;
    teacherId: bigint;
    classLevel: string;
}
export interface Certificate {
    issueDate: string;
    certId: bigint;
    studentId: bigint;
    certNumber: string;
    courseName: string;
}
export interface UserProfile {
    userId: bigint;
    name: string;
    createdAt: bigint;
    role: AppRole;
    email: string;
    phone: string;
}
export interface Student {
    studentId: bigint;
    enrolledPlanId: bigint;
    name: string;
    isActive: boolean;
    referredBy?: bigint;
    classLevel: string;
    parentId: bigint;
    syllabus: string;
    medium: string;
}
export enum AppRole {
    Parent = "Parent",
    Teacher = "Teacher",
    Student = "Student",
    FieldExecutive = "FieldExecutive",
    Admin = "Admin"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmPayment(paymentId: bigint, razorpayPaymentId: string): Promise<boolean>;
    createAttendanceRecord(record: AttendanceRecord): Promise<void>;
    createClassLevel(classLevel: ClassLevel): Promise<void>;
    createDemoBooking(booking: DemoBooking): Promise<void>;
    createHomework(homework: Homework): Promise<void>;
    createPayment(payment: Payment): Promise<void>;
    createPricingPlan(plan: PricingPlan): Promise<void>;
    createRazorpayOrder(studentId: bigint, planId: bigint): Promise<string>;
    createReferral(referral: Referral): Promise<void>;
    createScheduledClass(scheduledClass: ScheduledClass): Promise<void>;
    createStudent(student: Student): Promise<void>;
    createStudyMaterial(material: StudyMaterial): Promise<void>;
    createTestResult(result: TestResult): Promise<void>;
    deleteClassLevel(id: bigint): Promise<void>;
    deleteDemoBooking(bookingId: bigint): Promise<void>;
    deleteHomework(homeworkId: bigint): Promise<void>;
    deletePricingPlan(planId: bigint): Promise<void>;
    deleteScheduledClass(classId: bigint): Promise<void>;
    deleteStudent(studentId: bigint): Promise<void>;
    deleteStudyMaterial(materialId: bigint): Promise<void>;
    generateCertificate(studentId: bigint, courseName: string): Promise<Certificate>;
    getAllClassLevels(): Promise<Array<ClassLevel>>;
    getAllDemoBookings(): Promise<Array<DemoBooking>>;
    getAllPricingPlans(): Promise<Array<PricingPlan>>;
    getAllStudyMaterials(): Promise<Array<StudyMaterial>>;
    getAttendanceByStudent(studentId: bigint): Promise<Array<AttendanceRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCertificatesByStudent(studentId: bigint): Promise<Array<Certificate>>;
    getClassSchedule(classLevel: string): Promise<Array<ScheduledClass>>;
    getDemoBooking(bookingId: bigint): Promise<DemoBooking>;
    getHomeworkByClass(classLevel: string): Promise<Array<Homework>>;
    getPaymentsByStudent(studentId: bigint): Promise<Array<Payment>>;
    getReferralsByFieldExec(fieldExecId: bigint): Promise<Array<Referral>>;
    getStudent(studentId: bigint): Promise<Student>;
    getStudentsByParent(parentId: bigint): Promise<Array<Student>>;
    getStudentsByTeacher(teacherId: bigint): Promise<Array<Student>>;
    getStudyMaterials(classLevel: string): Promise<Array<StudyMaterial>>;
    getTestResults(studentId: bigint): Promise<Array<TestResult>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(userId: bigint): Promise<AppRole | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClassLevel(classLevel: ClassLevel): Promise<void>;
    updateDemoBooking(booking: DemoBooking): Promise<void>;
    updateHomework(homework: Homework): Promise<void>;
    updatePricingPlan(plan: PricingPlan): Promise<void>;
    updateScheduledClass(scheduledClass: ScheduledClass): Promise<void>;
    updateStudent(student: Student): Promise<void>;
    updateStudyMaterial(material: StudyMaterial): Promise<void>;
}
import type { AppRole as _AppRole, Student as _Student, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmPayment(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0, arg1);
            return result;
        }
    }
    async createAttendanceRecord(arg0: AttendanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAttendanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAttendanceRecord(arg0);
            return result;
        }
    }
    async createClassLevel(arg0: ClassLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClassLevel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClassLevel(arg0);
            return result;
        }
    }
    async createDemoBooking(arg0: DemoBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDemoBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDemoBooking(arg0);
            return result;
        }
    }
    async createHomework(arg0: Homework): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHomework(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHomework(arg0);
            return result;
        }
    }
    async createPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0);
            return result;
        }
    }
    async createPricingPlan(arg0: PricingPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPricingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPricingPlan(arg0);
            return result;
        }
    }
    async createRazorpayOrder(arg0: bigint, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayOrder(arg0, arg1);
            return result;
        }
    }
    async createReferral(arg0: Referral): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReferral(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReferral(arg0);
            return result;
        }
    }
    async createScheduledClass(arg0: ScheduledClass): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createScheduledClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScheduledClass(arg0);
            return result;
        }
    }
    async createStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(to_candid_Student_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(to_candid_Student_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStudyMaterial(arg0: StudyMaterial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudyMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudyMaterial(arg0);
            return result;
        }
    }
    async createTestResult(arg0: TestResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestResult(arg0);
            return result;
        }
    }
    async deleteClassLevel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClassLevel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClassLevel(arg0);
            return result;
        }
    }
    async deleteDemoBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDemoBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDemoBooking(arg0);
            return result;
        }
    }
    async deleteHomework(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHomework(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHomework(arg0);
            return result;
        }
    }
    async deletePricingPlan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePricingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePricingPlan(arg0);
            return result;
        }
    }
    async deleteScheduledClass(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduledClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduledClass(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteStudyMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudyMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudyMaterial(arg0);
            return result;
        }
    }
    async generateCertificate(arg0: bigint, arg1: string): Promise<Certificate> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCertificate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCertificate(arg0, arg1);
            return result;
        }
    }
    async getAllClassLevels(): Promise<Array<ClassLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClassLevels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClassLevels();
            return result;
        }
    }
    async getAllDemoBookings(): Promise<Array<DemoBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDemoBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDemoBookings();
            return result;
        }
    }
    async getAllPricingPlans(): Promise<Array<PricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPricingPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPricingPlans();
            return result;
        }
    }
    async getAllStudyMaterials(): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudyMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudyMaterials();
            return result;
        }
    }
    async getAttendanceByStudent(arg0: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByStudent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificatesByStudent(arg0: bigint): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificatesByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificatesByStudent(arg0);
            return result;
        }
    }
    async getClassSchedule(arg0: string): Promise<Array<ScheduledClass>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassSchedule(arg0);
            return result;
        }
    }
    async getDemoBooking(arg0: bigint): Promise<DemoBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemoBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemoBooking(arg0);
            return result;
        }
    }
    async getHomeworkByClass(arg0: string): Promise<Array<Homework>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeworkByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeworkByClass(arg0);
            return result;
        }
    }
    async getPaymentsByStudent(arg0: bigint): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByStudent(arg0);
            return result;
        }
    }
    async getReferralsByFieldExec(arg0: bigint): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralsByFieldExec(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralsByFieldExec(arg0);
            return result;
        }
    }
    async getStudent(arg0: bigint): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_Student_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_Student_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsByParent(arg0: bigint): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByParent(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByParent(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsByTeacher(arg0: bigint): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByTeacher(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByTeacher(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyMaterials(arg0: string): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterials(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterials(arg0);
            return result;
        }
    }
    async getTestResults(arg0: bigint): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResults(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: bigint): Promise<AppRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateClassLevel(arg0: ClassLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClassLevel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClassLevel(arg0);
            return result;
        }
    }
    async updateDemoBooking(arg0: DemoBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDemoBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDemoBooking(arg0);
            return result;
        }
    }
    async updateHomework(arg0: Homework): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomework(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomework(arg0);
            return result;
        }
    }
    async updatePricingPlan(arg0: PricingPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePricingPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePricingPlan(arg0);
            return result;
        }
    }
    async updateScheduledClass(arg0: ScheduledClass): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduledClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduledClass(arg0);
            return result;
        }
    }
    async updateStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(to_candid_Student_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(to_candid_Student_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStudyMaterial(arg0: StudyMaterial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudyMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudyMaterial(arg0);
            return result;
        }
    }
}
function from_candid_AppRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppRole]): AppRole | null {
    return value.length === 0 ? null : from_candid_AppRole_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: bigint;
    enrolledPlanId: bigint;
    name: string;
    isActive: boolean;
    referredBy: [] | [bigint];
    classLevel: string;
    parentId: bigint;
    syllabus: string;
    medium: string;
}): {
    studentId: bigint;
    enrolledPlanId: bigint;
    name: string;
    isActive: boolean;
    referredBy?: bigint;
    classLevel: string;
    parentId: bigint;
    syllabus: string;
    medium: string;
} {
    return {
        studentId: value.studentId,
        enrolledPlanId: value.enrolledPlanId,
        name: value.name,
        isActive: value.isActive,
        referredBy: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.referredBy)),
        classLevel: value.classLevel,
        parentId: value.parentId,
        syllabus: value.syllabus,
        medium: value.medium
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: bigint;
    name: string;
    createdAt: bigint;
    role: _AppRole;
    email: string;
    phone: string;
}): {
    userId: bigint;
    name: string;
    createdAt: bigint;
    role: AppRole;
    email: string;
    phone: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_AppRole_n8(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Parent: null;
} | {
    Teacher: null;
} | {
    Student: null;
} | {
    FieldExecutive: null;
} | {
    Admin: null;
}): AppRole {
    return "Parent" in value ? AppRole.Parent : "Teacher" in value ? AppRole.Teacher : "Student" in value ? AppRole.Student : "FieldExecutive" in value ? AppRole.FieldExecutive : "Admin" in value ? AppRole.Admin : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n12(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Student_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Student): _Student {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: bigint;
    name: string;
    createdAt: bigint;
    role: AppRole;
    email: string;
    phone: string;
}): {
    userId: bigint;
    name: string;
    createdAt: bigint;
    role: _AppRole;
    email: string;
    phone: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_AppRole_n19(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: bigint;
    enrolledPlanId: bigint;
    name: string;
    isActive: boolean;
    referredBy?: bigint;
    classLevel: string;
    parentId: bigint;
    syllabus: string;
    medium: string;
}): {
    studentId: bigint;
    enrolledPlanId: bigint;
    name: string;
    isActive: boolean;
    referredBy: [] | [bigint];
    classLevel: string;
    parentId: bigint;
    syllabus: string;
    medium: string;
} {
    return {
        studentId: value.studentId,
        enrolledPlanId: value.enrolledPlanId,
        name: value.name,
        isActive: value.isActive,
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none(),
        classLevel: value.classLevel,
        parentId: value.parentId,
        syllabus: value.syllabus,
        medium: value.medium
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Parent: null;
} | {
    Teacher: null;
} | {
    Student: null;
} | {
    FieldExecutive: null;
} | {
    Admin: null;
} {
    return value == AppRole.Parent ? {
        Parent: null
    } : value == AppRole.Teacher ? {
        Teacher: null
    } : value == AppRole.Student ? {
        Student: null
    } : value == AppRole.FieldExecutive ? {
        FieldExecutive: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
